/**
 * !!! THIS FILE IS AUTOGENERATED !!!
 *
 * This file will be overwritten with the definitions of the device profile
 * of the customer upon delivery. So, don't modify this file
 * directly, better modify the device profile description.
 */

#ifndef __PROFILE__H__
#define __PROFILE__H__
/* Priority 1*/



#define COMPO_INIT_DECLS \
int SysTimer__Entry(INIT_STRUCT *pInitStruct); \
int SysTimeRtc__Entry(INIT_STRUCT *pInitStruct); \
int SysTime__Entry(INIT_STRUCT *pInitStruct); \
int SysTask__Entry(INIT_STRUCT *pInitStruct); \
int SysTarget__Entry(INIT_STRUCT *pInitStruct); \
int SysSocket__Entry(INIT_STRUCT *pInitStruct); \
int SysShm__Entry(INIT_STRUCT *pInitStruct); \
int SysSemProcess__Entry(INIT_STRUCT *pInitStruct); \
int SysSemCount__Entry(INIT_STRUCT *pInitStruct); \
int SysSem__Entry(INIT_STRUCT *pInitStruct); \
int SysReadWriteLock__Entry(INIT_STRUCT *pInitStruct); \
int SysProcess__Entry(INIT_STRUCT *pInitStruct); \
int SysOut__Entry(INIT_STRUCT *pInitStruct); \
int SysMutex__Entry(INIT_STRUCT *pInitStruct); \
int SysMsgQ__Entry(INIT_STRUCT *pInitStruct); \
int SysModule__Entry(INIT_STRUCT *pInitStruct); \
int SysMem__Entry(INIT_STRUCT *pInitStruct); \
int SysInternalLib__Entry(INIT_STRUCT *pInitStruct); \
int SysFile__Entry(INIT_STRUCT *pInitStruct); \
int SysExcept__Entry(INIT_STRUCT *pInitStruct); \
int SysEvent__Entry(INIT_STRUCT *pInitStruct); \
int SysEthernet__Entry(INIT_STRUCT *pInitStruct); \
int SysDir__Entry(INIT_STRUCT *pInitStruct); \
int SysCpuHandling__Entry(INIT_STRUCT *pInitStruct); \
int SysCom__Entry(INIT_STRUCT *pInitStruct); \
int CmpWebServerHandlerV3__Entry(INIT_STRUCT *pInitStruct); \
int CmpWebServer__Entry(INIT_STRUCT *pInitStruct); \
int CmpVisuServer__Entry(INIT_STRUCT *pInitStruct); \
int CmpVisuHandler__Entry(INIT_STRUCT *pInitStruct); \
int CmpUserMgr__Entry(INIT_STRUCT *pInitStruct); \
int CmpUserDBObjects__Entry(INIT_STRUCT *pInitStruct); \
int CmpUserDB__Entry(INIT_STRUCT *pInitStruct); \
int CmpTraceMgr__Entry(INIT_STRUCT *pInitStruct); \
int CmpSrv__Entry(INIT_STRUCT *pInitStruct); \
int CmpSettings__Entry(INIT_STRUCT *pInitStruct); \
int CmpSchedule__Entry(INIT_STRUCT *pInitStruct); \
int CmpRouter__Entry(INIT_STRUCT *pInitStruct); \
int CmpRetain__Entry(INIT_STRUCT *pInitStruct); \
int CmpPlcShell__Entry(INIT_STRUCT *pInitStruct); \
int CmpOpenSSL__Entry(INIT_STRUCT *pInitStruct); \
int CmpOPCUAStack__Entry(INIT_STRUCT *pInitStruct); \
int CmpOPCUAServer__Entry(INIT_STRUCT *pInitStruct); \
int CmpOPCUAProviderIecVarAccess__Entry(INIT_STRUCT *pInitStruct); \
int CmpNameServiceServer__Entry(INIT_STRUCT *pInitStruct); \
int CmpNameServiceClientIec__Entry(INIT_STRUCT *pInitStruct); \
int CmpNameServiceClient__Entry(INIT_STRUCT *pInitStruct); \
int CmpMonitor2__Entry(INIT_STRUCT *pInitStruct); \
int CmpMemPool__Entry(INIT_STRUCT *pInitStruct); \
int CmpLog__Entry(INIT_STRUCT *pInitStruct); \
int CmpIoMgr__Entry(INIT_STRUCT *pInitStruct); \
int CmpIoDrvIec__Entry(INIT_STRUCT *pInitStruct); \
int CmpIecVarAccess__Entry(INIT_STRUCT *pInitStruct); \
int CmpIecTask__Entry(INIT_STRUCT *pInitStruct); \
int CmpIecStringUtils__Entry(INIT_STRUCT *pInitStruct); \
int CmpFileTransfer__Entry(INIT_STRUCT *pInitStruct); \
int CmpEventMgr__Entry(INIT_STRUCT *pInitStruct); \
int CmpEL6751CanDrv__Entry(INIT_STRUCT *pInitStruct); \
int CmpDynamicText__Entry(INIT_STRUCT *pInitStruct); \
int CmpDevice__Entry(INIT_STRUCT *pInitStruct); \
int CmpCryptMD5__Entry(INIT_STRUCT *pInitStruct); \
int CmpCoreDump__Entry(INIT_STRUCT *pInitStruct); \
int CmpCommunicationLib__Entry(INIT_STRUCT *pInitStruct); \
int CmpCodeMeter__Entry(INIT_STRUCT *pInitStruct); \
int CmpChecksum__Entry(INIT_STRUCT *pInitStruct); \
int CmpCharDevice__Entry(INIT_STRUCT *pInitStruct); \
int CmpChannelServer__Entry(INIT_STRUCT *pInitStruct); \
int CmpChannelMgr__Entry(INIT_STRUCT *pInitStruct); \
int CmpChannelClientIec__Entry(INIT_STRUCT *pInitStruct); \
int CmpChannelClient__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAATypes__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAATimer__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAATickUtil__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAATick__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAAStorage__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAASerialCom__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAASegBufferMan__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAASdoServer__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAASdoClient__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAARealTimeClock__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAANetBaseServices__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAAMemBlockMan__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAAFile__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAADTUtil__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAACanL2__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAACallback__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAABehaviourModel__Entry(INIT_STRUCT *pInitStruct); \
int CmpCAAAsyncMan__Entry(INIT_STRUCT *pInitStruct); \
int CmpBlkDrvUdp__Entry(INIT_STRUCT *pInitStruct); \
int CmpBlkDrvTcp__Entry(INIT_STRUCT *pInitStruct); \
int CmpBlkDrvCom__Entry(INIT_STRUCT *pInitStruct); \
int CmpBitmapPool__Entry(INIT_STRUCT *pInitStruct); \
int CmpBinTagUtilIec__Entry(INIT_STRUCT *pInitStruct); \
int CmpBinTagUtil__Entry(INIT_STRUCT *pInitStruct); \
int CmpAsyncMgr__Entry(INIT_STRUCT *pInitStruct); \
int CmpAppForce__Entry(INIT_STRUCT *pInitStruct); \
int CmpAppBP__Entry(INIT_STRUCT *pInitStruct); \
int CmpApp__Entry(INIT_STRUCT *pInitStruct); \
int CmpAlarmManager__Entry(INIT_STRUCT *pInitStruct); \
int CM__Entry(INIT_STRUCT *pInitStruct);


#define COMPO_INIT_LIST \
{"SysTimer", SysTimer__Entry, 0}, \
{"SysTimeRtc", SysTimeRtc__Entry, 0}, \
{"SysTime", SysTime__Entry, 0}, \
{"SysTask", SysTask__Entry, 0}, \
{"SysTarget", SysTarget__Entry, 0}, \
{"SysSocket", SysSocket__Entry, 0}, \
{"SysShm", SysShm__Entry, 0}, \
{"SysSemProcess", SysSemProcess__Entry, 0}, \
{"SysSemCount", SysSemCount__Entry, 0}, \
{"SysSem", SysSem__Entry, 0}, \
{"SysReadWriteLock", SysReadWriteLock__Entry, 0}, \
{"SysProcess", SysProcess__Entry, 0}, \
{"SysOut", SysOut__Entry, 0}, \
{"SysMutex", SysMutex__Entry, 0}, \
{"SysMsgQ", SysMsgQ__Entry, 0}, \
{"SysModule", SysModule__Entry, 0}, \
{"SysMem", SysMem__Entry, 0}, \
{"SysInternalLib", SysInternalLib__Entry, 0}, \
{"SysFile", SysFile__Entry, 0}, \
{"SysExcept", SysExcept__Entry, 0}, \
{"SysEvent", SysEvent__Entry, 0}, \
{"SysEthernet", SysEthernet__Entry, 0}, \
{"SysDir", SysDir__Entry, 0}, \
{"SysCpuHandling", SysCpuHandling__Entry, 0}, \
{"SysCom", SysCom__Entry, 0}, \
{"CmpWebServerHandlerV3", CmpWebServerHandlerV3__Entry, 0}, \
{"CmpWebServer", CmpWebServer__Entry, 0}, \
{"CmpVisuServer", CmpVisuServer__Entry, 0}, \
{"CmpVisuHandler", CmpVisuHandler__Entry, 0}, \
{"CmpUserMgr", CmpUserMgr__Entry, 0}, \
{"CmpUserDBObjects", CmpUserDBObjects__Entry, 0}, \
{"CmpUserDB", CmpUserDB__Entry, 0}, \
{"CmpTraceMgr", CmpTraceMgr__Entry, 0}, \
{"CmpSrv", CmpSrv__Entry, 0}, \
{"CmpSettings", CmpSettings__Entry, 0}, \
{"CmpSchedule", CmpSchedule__Entry, 0}, \
{"CmpRouter", CmpRouter__Entry, 0}, \
{"CmpRetain", CmpRetain__Entry, 0}, \
{"CmpPlcShell", CmpPlcShell__Entry, 0}, \
{"CmpOpenSSL", CmpOpenSSL__Entry, 0}, \
/*{"CmpOPCUAStack", CmpOPCUAStack__Entry, 0}, \
{"CmpOPCUAServer", CmpOPCUAServer__Entry, 0}, \
{"CmpOPCUAProviderIecVarAccess", CmpOPCUAProviderIecVarAccess__Entry, 0}, \
*/{"CmpNameServiceServer", CmpNameServiceServer__Entry, 0}, \
{"CmpNameServiceClientIec", CmpNameServiceClientIec__Entry, 0}, \
{"CmpNameServiceClient", CmpNameServiceClient__Entry, 0}, \
{"CmpMonitor2", CmpMonitor2__Entry, 0}, \
{"CmpMemPool", CmpMemPool__Entry, 0}, \
{"CmpLog", CmpLog__Entry, 0}, \
{"CmpIoMgr", CmpIoMgr__Entry, 0}, \
{"CmpIoDrvIec", CmpIoDrvIec__Entry, 0}, \
{"CmpIecVarAccess", CmpIecVarAccess__Entry, 0}, \
{"CmpIecTask", CmpIecTask__Entry, 0}, \
{"CmpIecStringUtils", CmpIecStringUtils__Entry, 0}, \
{"CmpFileTransfer", CmpFileTransfer__Entry, 0}, \
{"CmpEventMgr", CmpEventMgr__Entry, 0}, \
{"CmpEL6751CanDrv", CmpEL6751CanDrv__Entry, 0}, \
{"CmpDynamicText", CmpDynamicText__Entry, 0}, \
{"CmpDevice", CmpDevice__Entry, 0}, \
{"CmpCryptMD5", CmpCryptMD5__Entry, 0}, \
{"CmpCoreDump", CmpCoreDump__Entry, 0}, \
{"CmpCommunicationLib", CmpCommunicationLib__Entry, 0}, \
{"CmpCodeMeter", CmpCodeMeter__Entry, 0}, \
{"CmpChecksum", CmpChecksum__Entry, 0}, \
{"CmpCharDevice", CmpCharDevice__Entry, 0}, \
{"CmpChannelServer", CmpChannelServer__Entry, 0}, \
{"CmpChannelMgr", CmpChannelMgr__Entry, 0}, \
{"CmpChannelClientIec", CmpChannelClientIec__Entry, 0}, \
{"CmpChannelClient", CmpChannelClient__Entry, 0}, \
{"CmpCAATypes", CmpCAATypes__Entry, 0}, \
{"CmpCAATimer", CmpCAATimer__Entry, 0}, \
{"CmpCAATickUtil", CmpCAATickUtil__Entry, 0}, \
{"CmpCAATick", CmpCAATick__Entry, 0}, \
{"CmpCAAStorage", CmpCAAStorage__Entry, 0}, \
{"CmpCAASerialCom", CmpCAASerialCom__Entry, 0}, \
{"CmpCAASegBufferMan", CmpCAASegBufferMan__Entry, 0}, \
{"CmpCAASdoServer", CmpCAASdoServer__Entry, 0}, \
{"CmpCAASdoClient", CmpCAASdoClient__Entry, 0}, \
{"CmpCAARealTimeClock", CmpCAARealTimeClock__Entry, 0}, \
{"CmpCAANetBaseServices", CmpCAANetBaseServices__Entry, 0}, \
{"CmpCAAMemBlockMan", CmpCAAMemBlockMan__Entry, 0}, \
{"CmpCAAFile", CmpCAAFile__Entry, 0}, \
{"CmpCAADTUtil", CmpCAADTUtil__Entry, 0}, \
{"CmpCAACanL2", CmpCAACanL2__Entry, 0}, \
{"CmpCAACallback", CmpCAACallback__Entry, 0}, \
{"CmpCAABehaviourModel", CmpCAABehaviourModel__Entry, 0}, \
{"CmpCAAAsyncMan", CmpCAAAsyncMan__Entry, 0}, \
{"CmpBlkDrvUdp", CmpBlkDrvUdp__Entry, 0}, \
{"CmpBlkDrvTcp", CmpBlkDrvTcp__Entry, 0}, \
{"CmpBlkDrvCom", CmpBlkDrvCom__Entry, 0}, \
{"CmpBitmapPool", CmpBitmapPool__Entry, 0}, \
{"CmpBinTagUtilIec", CmpBinTagUtilIec__Entry, 0}, \
{"CmpBinTagUtil", CmpBinTagUtil__Entry, 0}, \
{"CmpAsyncMgr", CmpAsyncMgr__Entry, 0}, \
{"CmpAppForce", CmpAppForce__Entry, 0}, \
{"CmpAppBP", CmpAppBP__Entry, 0}, \
{"CmpApp", CmpApp__Entry, 0}, \
{"CmpAlarmManager", CmpAlarmManager__Entry, 0}, \
{"CM", CM__Entry, 0}




#define CMPMEMGC_NOTIMPLEMENTED
#define CMPMONITOR_NOTIMPLEMENTED
#define CMPOBJECTMGR_NOTIMPLEMENTED
#define CMPSIL2_NOTIMPLEMENTED
#define CMPSECURECHANNEL_NOTIMPLEMENTED
#define CMPSECURITYMANAGER_NOTIMPLEMENTED
#define CMPSUPERVISOR_NOTIMPLEMENTED
#define CMPTARGETVISU_NOTIMPLEMENTED
#define CMPXMLPARSER_NOTIMPLEMENTED
#define SYSCPUBREAKPOINTS_NOTIMPLEMENTED
#define SYSCPUMULTICORE_NOTIMPLEMENTED
#define SYSFLASH_NOTIMPLEMENTED
#define SYSINT_NOTIMPLEMENTED
#define SYSUSERDB_NOTIMPLEMENTED




/* Priority 2*/



/* Priority 3*/



/* Priority 4*/



/* Priority 5*/



/* Priority 6*/



/* Priority 7*/



/* Priority 8*/



/* Priority 9*/



/* Priority 10*/



#endif /* __PROFILE__H__ */
