/**
 * !!! THIS FILE IS AUTOGENERATED !!!
 *
 * This file will be overwritten with the target definitions
 * of the customer upon delivery. So, don't modify this file
 * directly!
 */

#ifndef __TARGETDEFINES_H_
#define __TARGETDEFINES_H_

#ifndef SYSTARGET_SIGNATUREID
	#define SYSTARGET_SIGNATUREID 0xAB3B94CC
#endif

#ifndef SYSTARGET_DEVICE_TYPE
	#define SYSTARGET_DEVICE_TYPE 4102
#endif

#ifndef SYSTARGET_VENDOR_ID
	#define SYSTARGET_VENDOR_ID   0x1688
#endif

#ifndef SYSTARGET_DEVICE_ID
	#define SYSTARGET_DEVICE_ID   0x0002
#endif

#ifndef SYSTARGET_DEVICE_MASK
	#define SYSTARGET_DEVICE_MASK 0x0000
#endif

#ifndef SYSTARGET_VENDOR_NAME
	#define SYSTARGET_VENDOR_NAME "Changsha Xiangji Hiden Technology Co.Ltd"
#endif

#ifndef SYSTARGET_DEVICE_NAME
	#define SYSTARGET_DEVICE_NAME "Changsha Xiangji-ARM Cortex A9(xilinx zynq7000)-linux"
#endif

#ifndef SYSTARGET_DEVICE_VERSION
	#define SYSTARGET_DEVICE_VERSION 0x03050c01
#endif

/*#ifndef TRG_ARM
	#define TRG_ARM
#endif*/

#endif /* __TARGETDEFINES_H_ */
